name: Unpack ZIP

on:
  push:
    paths:
      - "RAg.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip file
        run: unzip -o RAg.zip -d .

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-unpack RAg.zip" || echo "No changes"
          git push
