name: Auto-Unpack ZIP

on:
  push:
    branches:
      - main

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Unpack RAg.zip if exists
        run: |
          if [ -f RAg.zip ]; then
            unzip -o RAg.zip -d .
          else
            echo "RAg.zip not found, skipping."
          fi
